// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Block-level attributes
class BlockAttrs {
  final int? level;
  final String? language;

  const BlockAttrs({this.level, this.language});

  @override
  int get hashCode => level.hashCode ^ language.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlockAttrs &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          language == other.language;
}

enum BlockType {
  paragraph,
  heading,
  bulletList,
  orderedList,
  codeBlock,
  blockquote,
}

class Content {
  final String text;
  final List<ContentBlock> blocks;

  const Content({required this.text, required this.blocks});

  @override
  int get hashCode => text.hashCode ^ blocks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Content &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          blocks == other.blocks;
}

class ContentBlock {
  final BlockType blockType;
  final List<InlineElement> content;
  final BlockAttrs? attrs;

  const ContentBlock({
    required this.blockType,
    required this.content,
    this.attrs,
  });

  @override
  int get hashCode => blockType.hashCode ^ content.hashCode ^ attrs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContentBlock &&
          runtimeType == other.runtimeType &&
          blockType == other.blockType &&
          content == other.content &&
          attrs == other.attrs;
}

/// Inline content with optional formatting marks
class InlineElement {
  final InlineType inlineType;
  final String text;
  final List<TextMark>? marks;

  const InlineElement({
    required this.inlineType,
    required this.text,
    this.marks,
  });

  @override
  int get hashCode => inlineType.hashCode ^ text.hashCode ^ marks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InlineElement &&
          runtimeType == other.runtimeType &&
          inlineType == other.inlineType &&
          text == other.text &&
          marks == other.marks;
}

enum InlineType { text, hardBreak }

class MarkAttrs {
  final String? href;

  const MarkAttrs({this.href});

  @override
  int get hashCode => href.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarkAttrs &&
          runtimeType == other.runtimeType &&
          href == other.href;
}

enum MarkType { bold, italic, underline, strikethrough, code, link }

class TextMark {
  final MarkType markType;
  final MarkAttrs? attrs;

  const TextMark({required this.markType, this.attrs});

  @override
  int get hashCode => markType.hashCode ^ attrs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextMark &&
          runtimeType == other.runtimeType &&
          markType == other.markType &&
          attrs == other.attrs;
}
