// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'base_models.dart';
import 'contents.dart';
import 'nodes.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'relations.dart';
import 'styles.dart';
import 'tags.dart';

class GraphSnapshot {
  final List<Nodes> nodes;
  final List<IRelation> relations;
  final MapData metadata;

  const GraphSnapshot({
    required this.nodes,
    required this.relations,
    required this.metadata,
  });

  @override
  int get hashCode => nodes.hashCode ^ relations.hashCode ^ metadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GraphSnapshot &&
          runtimeType == other.runtimeType &&
          nodes == other.nodes &&
          relations == other.relations &&
          metadata == other.metadata;
}
