// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'base_models.dart';
import 'contents.dart';
import 'nodes.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'relations.dart';
import 'styles.dart';
import 'tags.dart';

class Template {
  final String key;
  final String name;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final List<Nodes> nodes;
  final List<IRelation> relations;

  const Template({
    required this.key,
    required this.name,
    required this.createdAt,
    required this.updatedAt,
    required this.nodes,
    required this.relations,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      name.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      nodes.hashCode ^
      relations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Template &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          name == other.name &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          nodes == other.nodes &&
          relations == other.relations;
}
