// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/base_models.dart';
import '../domain/contents.dart';
import '../domain/nodes.dart';
import '../domain/patches.dart';
import '../domain/relations.dart';
import '../domain/snapshot.dart';
import '../domain/styles.dart';
import '../domain/tags.dart';
import '../domain/templates.dart';
import '../domain/theme.dart';
import '../frb_generated.dart';
import '../persistence/history.dart';
import '../persistence/repo.dart';
import '../telemetry.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'stream.dart';

// These functions are ignored because they are not marked as `pub`: `apply_history_record_patch`, `broadcast_boundaries`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

Future<void> setupLogger() => RustLib.instance.api.crateBridgeApiSetupLogger();

Stream<LogState> createLogStream() =>
    RustLib.instance.api.crateBridgeApiCreateLogStream();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppHandle>>
abstract class AppHandle implements RustOpaqueInterface {
  Future<void> applyEntityMutation({required SymmetricEntityPatch mutation});

  Repository get repo;

  set repo(Repository repo);

  Future<void> close();

  Stream<GraphEvent> createGraphStream();

  Future<void> createNode({required Nodes input});

  Future<void> createRelation({required IRelation input});

  Future<void> createTag({required Tag tag});

  Future<void> createTheme({required String key, required ThemeFields fields});

  Future<void> deleteNodeEntry({required String table, required String key});

  Future<void> deleteRelation({required String table, required String key});

  Future<void> deleteTag({required String key});

  Future<void> deleteTemplate({required String key});

  Future<String?> getActiveThemeId();

  Future<List<Tag>> getAllTags();

  Future<List<Template>> getAllTemplates();

  Future<List<Theme>> getAllThemes();

  Future<GraphSnapshot> getGraphSnapshot();

  Future<Nodes?> getNode({required String table, required String key});

  Future<Tag?> getTag({required String key});

  Future<Theme?> getTheme({required String key});

  Future<void> instantiateTemplate({
    required String key,
    required double targetX,
    required double targetY,
  });

  Future<void> loadMapFromFile({
    required String filePath,
    required String attachmentDir,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AppHandle> newInstance({
    required String storagePath,
    required String name,
  }) => RustLib.instance.api.crateBridgeApiAppHandleNew(
    storagePath: storagePath,
    name: name,
  );

  Future<List<Nodes>> querySearch({required String query});

  Future<HistoryRecord?> redo();

  Future<int> redoCount();

  Future<void> rerouteRelation({
    required RecordStrings record,
    required RecordStrings from,
    required RecordStrings to,
  });

  Future<void> saveMapToFile({
    required String filePath,
    required String attachmentDir,
  });

  Future<void> saveTemplateFromSelection({
    required String name,
    required List<RecordStrings> nodeKeys,
    required List<RecordStrings> relationKeys,
  });

  Future<void> setActiveTheme({required String themeKey});

  Future<void> setActiveThemeId({required String themeId});

  Future<HistoryRecord?> undo();

  Future<int> undoCount();

  Future<void> updateNode({required Nodes input});

  Future<void> updateRelation({required IRelation input});

  Future<void> updateTag({required Tag tag});

  Future<void> updateTheme({required Theme theme});

  Future<void> updateViewportState({required ViewportState state});

  static Future<AppHandle> withRepository({required Repository repo}) =>
      RustLib.instance.api.crateBridgeApiAppHandleWithRepository(repo: repo);
}
