// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/base_models.dart';
import '../domain/contents.dart';
import '../domain/nodes.dart';
import '../domain/styles.dart';
import '../domain/tags.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'stream.freezed.dart';

@freezed
sealed class GraphEvent with _$GraphEvent {
  const GraphEvent._();

  const factory GraphEvent.nodeUpdated(Nodes field0) = GraphEvent_NodeUpdated;
  const factory GraphEvent.nodeDeleted(String field0) = GraphEvent_NodeDeleted;
  const factory GraphEvent.relationUpdated() = GraphEvent_RelationUpdated;
  const factory GraphEvent.snapshotLoaded() = GraphEvent_SnapshotLoaded;
  const factory GraphEvent.boundaryUpdated(BoundingBox field0) =
      GraphEvent_BoundaryUpdated;
}
